[project]
name = "dags"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apache-airflow>=2.10.5",
]

[project.scripts]
dags = "dags:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
